# Generated by Django 4.0.5 on 2022-06-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aricle',
            new_name='article',
        ),
    ]
